### ISSUE TITLE
Can I have the code?

### ISSUE THREAD

**Issue by AlejandraM97** [dbp1994/masters_thesis_codes#2]
Hi!

I would like to have the code of your master conference:)

**Comment by dbp1994** [comment]
Hi,

Thanks for your interest. The codes are available in the BARE and Memorization repositories. Those are the two papers that formed the basis of my Master's thesis. Hope that helps!

**Comment by AlejandraM97** [comment]
Hi,

Thanks for the replying, but unfortunately when I try to enter in the BARE and Memorization repositories it says "Page not found"

**Comment by dbp1994** [comment]
Hi, I am not sure why that's the case because both repositories are public. I am sharing the links here in the hope that it works this time:

- PAKDD 2021 paper on memorization - https://github.com/dbp1994/memorization-pakdd-2021
- WACV 2023 paper on adaptive sample selection - https://github.com/dbp1994/bare-wacv-2023

**Comment by AlejandraM97** [comment]
Thank you!! Now i can see each repository:3
